<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../InheritancePlayground.Application/InheritancePlayground.Application.csproj" />
    <ProjectReference Include="..\InheritancePlayground.Domain\InheritancePlayground.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
</PropertyGroup>

</Project>
